### ISSUE TITLE
Compare API

### ISSUE THREAD

**Issue by herryswastika** [tinfot/faceplusplus#4]
Is there a function for Compare API ? I mean, comparing two faces

**Comment by tinfot** [comment]
Sure, I will append on the next version.

**Comment by tinfot** [comment]
About 2 hours.

**Comment by herryswastika** [comment]
that was fast. thanks man. will try it tonight. 
about the server, api-us and api-cn, is there a different? i mean in term of speed, bandwidth, etc ? i live in indonesia.
thanks

**Comment by tinfot** [comment]
Hi bro, I Add a new configuration `base url`, I think you can try both. 
Choose the one you think is fast. : )

**Comment by herryswastika** [comment]
Hi,
I have an error : Class Face\FaceServiceProvider not found.

**Comment by herryswastika** [comment]
I am sorry, it seems from previous package, not yours.

**Comment by herryswastika** [comment]
AWESOME!! Works as expected

Thanks a lot

**Comment by herryswastika** [comment]
Thank you again for your package.

**Comment by tinfot** [comment]
Glad to help you.
